app/main/posts/forms.py
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError
from wtforms import StringField, PasswordField, SubmitField, BooleanField,TextAreaField,RadioField
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed

class Post(FlaskForm):
    
    title=StringField('Title', validators=[DataRequired()])
    description=TextAreaField('Description', validators=[DataRequired(),Length(min=2, max=300)])
    content=TextAreaField('Content', validators=[DataRequired(),Length(min=2)])
    # blog_image= FileField('Post Image', validators=[FileAllowed(['jpg','png','svg','jpeg','gif'])])
    submit = SubmitField('Create Post')
    

    
class CommentsForm(FlaskForm):
    content=TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Add')

app/main/posts/views.py
from email.mime import image
from pdb import main
from flask import Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app.main.posts.forms import CommentsForm, Post
from app.models import Posts,Comments
from werkzeug.utils import secure_filename
from app import db, mail
from flask_mail import  Message
from flask import render_template, url_for, flash, redirect, request
posts= Blueprint('posts',__name__)


@posts.route('/')
def home():
    
    # comm=Comments.query.all()
    posts = Posts.query.order_by(Posts.date_created.desc())

    # headline=Posts.query.filter_by(id=1).first()
    

    return render_template('index.html', posts = posts )



@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create():
    form = Post()
    if form.validate_on_submit():
    
        post = Posts(title=form.title.data,content=form.content.data,description=form.description.data, user_id=current_user.id)

        db.session.add(post)  
        db.session.commit()

        return redirect(url_for('posts.home'))

    else:
          flash('blog not added','danger')
          
    return render_template('post.html', form=form, title='Blog Post')

@login_required
@posts.route('/post/edit/<postid>',methods=['POST', 'GET'])
def post_edit(postid):
    form = Post()

    edites= Posts.query.filter_by(id=postid).first()
    
    if form.validate_on_submit():
        edites.title = form.title.data
        edites.content=form.content.data
        
        edites.description=form.description.data

        db.session.add(edites)
        db.session.commit()
        flash('thanks for your post','success')
        return redirect(url_for("main.home"))
    else:
        form.title.data=edites.title
        form.content.data=edites.content
        
        form.description.data=edites.description
    return render_template('editpost.html',form=form)

@posts.route('/post/delete/<postid>')
def post_delete(postid):
    post = Posts.query.get(postid)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('posts.home'))

@posts.route('/post/<postid>')
def reads(postid):

    reads= Posts.query.get(postid)

    

    return render_template('reads.html', posts=reads)
    

@posts.route('/comments/<id>',methods=['POST', 'GET'])
def comments(id):
    form = CommentsForm()
    posts = Posts.query.filter_by(id=id).first()
    if form.validate_on_submit():
        comment=Comments(comment=form.content.data,post_id=posts.id)
        # posts.comments+=form.content.data + '~'
        db.session.add(comment)
        db.session.commit()
        flash('comment added successfully','success')
        
        return redirect(url_for('posts.home'))
    form.content.data = ""
    return render_template('comments.html', form=form , posts=posts)


@posts.route('/comment/delete/<id>')
def comment_delete(id):
    comm = Comments.query.filter_by(id=id).first()
    
    db.session.delete(comm)
    db.session.commit()
    flash(' comment  deleted successfully','success')

    return redirect(url_for('posts.home'))

app/users/views.py
from flask import Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask import render_template, url_for, flash, redirect, request
from app.users.forms import Register, Login,UpdateAccountForm
from app import db,mail
from flask_mail import  Message
from werkzeug.security import generate_password_hash,check_password_hash
from app.models import Posts, User


users = Blueprint('users', __name__)

@users.route('/register', methods=['POST','GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('posts.home'))
    form = Register()
    if form.validate_on_submit():
      hashed_password = generate_password_hash(form.password.data).decode('utf8')
      user=User(username=form.username.data,email=form.email.data,password=hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Account Successfully Created! ','success')
      return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['POST', 'GET'])

def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.home'))
    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Welcome {user.username.title()} !! ', 'success')
            # args is a dict
            # get returns none if the next key does not exist
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('.home'))
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('posts.home'))

# @users.route('/subscribe', methods=['POST', 'GET'])
# def subscribe():
#     form=Subscribe()
#     if form.validate_on_submit():
        
        
#         db.session.add(sub)
#         db.session.commit()
#         msg=Message("WELCOME",sender="apollolibrary99@gmail.com",recipients=[sub.email])
#         msg.body = "Welcome to H&J's Blog you Have Subscribed News Letter we will loop you on all newly updates"
#         mail.send(msg)
     
#         flash('Your  Has Joined H&J Blog Subscription  ','success')
#         return redirect(url_for('main.home'))


#     return render_template('subscribe.html',form=form)

@users.route('/account',methods=['POST', 'GET'])
@login_required
def account():
    """
    """
    post= Posts.query.filter_by(user_id=current_user.id)
    form=UpdateAccountForm()
    if form.validate_on_submit():

        current_user.username=form.username.data
        current_user.email=form.email.data

        db.session.commit()
        flash('Your Account Has been updated!','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':

        form.username.data=current_user.username
        form.email.data=current_user.email
    
   
    return render_template('account.html', title='Account',form=form,post=post )

app/templates/2ndcoments.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
      
    <div class="row row-cols-1 row-cols-md-2 g-4">
  

      <div class="col ">
        <div class="card">
            <div class="row  p-2">
                <div class="col-md-8"></div>
             
              <div class="col-md-2 mx-auto mt-auto mb-auto text-muted">
                  <small>{{posts.author.username}}</small>
                  <br>
                  <small>{{posts.date_created.strftime('%Y-%m-%d')}}</small>
              </div>
            </div>
          <div class="card-body">
            <h5 class="card-title">{{posts.title}}</h5>
            <p class="card-text lead">{{posts.description}}</p>
            <div class="d-flex justify-content-around">
             
              <a  data-bs-toggle="collapse" href="#comments{{posts.id}}" class="lead text-decoration-none ">
                <img src="{{url_for('static',filename='/assets/comment.svg')}}" height="30" alt=""> 
              </a>
               
            </div>
            <div id="comments{{posts.id}}">

              <div class=" comments">

              
              </div>

              <div class="m-3">
                <form action="" method="post">
                  {{form.hidden_tag()}}
                  <div class="form-group">
                          {% if form.content.errors %}
                          {{form.content(class='form-control is-invalid')}}
                              {% for error in form.email.errors %}
                                  <div class="invalid-feedback">
                                      {{error}}
                                  </div>
                              {% endfor %}
                      {% else %}
                          {{form.content(class='form-control bg-transparent border border-light',placeholder='Enter Your Comment')}}
                      {% endif %}
                  </div>
                  <div class="text-center mt-3">
                    {{form.submit(class='btn btn-outline post_submit')}}
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
 
     
</div>
{% endblock %}

app/templates/account.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
<div class="row">
    <div class="col-md-6">
        <div class="container-fluid row p-5">
            <div class="col-md-4">
                <img src="{{image_file}}"  class="img-thumbnail img-fluid border border-white" alt="Profile picture" >
            </div>
            <div class="col-md-8 mx-auto mt-auto mb-auto  lead">
                <p>Username: {{ current_user.username.title() }}</p>
                
                <p><b>Email: {{ current_user.email }}</b></p>
               
                <a data-bs-toggle="collapse" href="#coll" class="text-decoration-none text-muted" >Update Info</a>
    
            </div>
        </div>
{%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/app/static/css/style.css">
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{{title}}</title>
</head>
<body>

  {% block navbar %}
     {% include 'navbar.html' %}
  {% endblock %}

  {% block body %}

  {% endblock %}



</body>   
</html>

app/templates/comments copy.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
      
    <div class="row row-cols-1 row-cols-md-2 g-4">
  

      <div class="col ">
        <div class="card">
            <div class="row  p-2">
                <div class="col-md-8"></div>
             
              <div class="col-md-2 mx-auto mt-auto mb-auto text-muted">
                  <small>{{posts.author.username}}</small>
                  <br>
                  <small>{{posts.date_created.strftime('%Y-%m-%d')}}</small>
              </div>
            </div>
          <div class="card-body">
            <h5 class="card-title">{{posts.title}}</h5>
            <p class="card-text lead">{{posts.description}}</p>
            <div class="d-flex justify-content-around">
             
              <a  data-bs-toggle="collapse" href="#comments{{posts.id}}" class="lead text-decoration-none ">
                <img src="{{url_for('static',filename='/assets/comment.svg')}}" height="30" alt=""> 
              </a>
               
            </div>
            <div id="comments{{posts.id}}">

              <div class=" comments">

              
              </div>

              <div class="m-3">
                <form action="" method="post">
                  {{form.hidden_tag()}}
                  <div class="form-group">
                          {% if form.content.errors %}
                          {{form.content(class='form-control is-invalid')}}
                              {% for error in form.email.errors %}
                                  <div class="invalid-feedback">
                                      {{error}}
                                  </div>
                              {% endfor %}
                      {% else %}
                          {{form.content(class='form-control bg-transparent border border-light',placeholder='Enter Your Comment')}}
                      {% endif %}
                  </div>
                  <div class="text-center mt-3">
                    {{form.submit(class='btn btn-outline post_submit')}}
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
 
     
</div>
{% endblock %}

app/templates/editpost.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid nav-page">
    <div class="container  bg-light mt-2 p-3">
        <form action="" method="post">
            {{form.hidden_tag()}}
            <legend class="border-bottom">New blog</legend>
          
            <div class="form-group">
                {{form.title.label(class='form-control-label')}}
                    {% if form.title.errors %}
                        {{form.title(class='form-control is-invalid')}}
                            {% for error in form.title.errors %}
                                <div class="invalid-feedback">
                                    {{error}}
                                </div>
                            {% endfor %}
                    {% else %}
                        {{form.title(class='form-control')}}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.content.label(class='form-control-label')}}
                    {% if form.content.errors %}
                    {{form.content(class='form-control is-invalid')}}
                        {% for error in form.content.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                {% else %}
                    {{form.content(class='form-control')}}
                {% endif %}
            </div>
            <div class="text-center my-3">
                {{form.submit(class='btn btn-outline')}}
            </div>
        </form>
     
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block body %}
  
  <div class="row">
    <div class="row">
     <div class="imress ">
       
      <p>
        share your thoughts <br> ispire . advise . boostmood
      </p>
             
     </div> 
  <a style="margin-left: 100px; text-align: center;" href="{{url_for('posts.create')}}" class="btn btn-lg btn-outline">POST BLOG</a>
    
      {% for post in posts %}
      <div style="margin-top: 80px;" class="col-md-4">
        <div class="card mx card-border" style="width:400px; color: white; text-align: center;padding: 30px; background-color: rgb(3, 30, 50); ">
          

          <div class="card-body mx-0 px-0">

            <div class="d-flex justify-content-between">

              <p class="text-muted">{{post.date_created.strftime('%Y-%m-%d')}}</p>
            </div>
            <h4 class="card-title mx-0 px-0">{{post.title}}</h4>
            <p class="card-text">{{post.description}}</p>

            <p class="fst-italic"> ~{{post.author.username}}</p>
  


            <div class="d-flex justify-content-between">
              
              <a style="text-decoration: none; padding: px; border-radius: 10px; background-color: red; color: white;" href="{{url_for('posts.post_delete',postid=post.id)}}">Delete post</a>
              <a style="text-decoration: none; padding: 10px; border-radius: 10px; background-color: green; color: white;" href="{{url_for('posts.post_edit',postid=post.id)}}">edit post</a>
              

             

            </div>
            <div class="collapse" id="comments{{post.id}}">
              


              <div class=" comments my-3">
                <p>Comments</p>
                <div class="card m-1">
                  {% for com in post.comments %}
                  <div class="d-flex justify-content-between">

                    <p class="lead fst-italic ">

                      {{com.comment}}
                      <div>

                        {% if current_user.id == post.author.id %}
                        <a href="{{url_for('posts.comment_delete',id=com.id)}}"
                          class="text-decoration-none delete">Delete</a>

                        {% endif %}
                      </div>

                    </p>
                  </div>
                  {% endfor %}



                </div>


              </div>

              <a href="{{url_for('posts.comments',id=post.id)}}" class="text-decoration-none text-muted">
                <img class="add my-4" src="{{url_for('static',filename='/assets/add.png')}}" alt="">Add
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

  </div>

</div>
<footer class="text-center bg-dark text-light">
  <i class="fa-brands fa-twitter"></i>
  <i class="fa-brands fa-facebook"></i>
  <i class="fa-brands fa-linkedin"></i>
  <i class="fa-brands fa-youtube"></i>
</footer>
{% endblock %}>

app/templates/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container nav-page">
    <div class="container nav-container bg-light mt-2 p-3">
        <form action="" method="post">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.email.label(class='form-control-label')}}
                    {% if form.email.errors %}
                    {{form.email(class='form-control is-invalid')}}
                        {% for error in form.email.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                {% else %}
                    {{form.email(class='form-control')}}
                {% endif %}
            </div>
            <div class="form-group my-3">
                {{form.password.label(class='form-control-label')}}
                {% if form.password.errors %}
                {{form.password(class='form-control is-invalid')}}
                    {% for error in form.password.errors %}
                        <div class="invalid-feedback">
                            {{error}}
                        </div>
                    {% endfor %}
            {% else %}
                {{form.password(class='form-control')}}
            {% endif %}
            </div>
            <!-- Remember -->
            <div class="form-check form-switch">
                {{form.remember.label(class='form-check-label')}}
                {{form.remember(class="form-check-input")}}
            </div>
            <div class="text-center mt-3">
                {{form.submit(class='btn btn-outline')}}
            </div>
            
        </form>
        <div class="text-muted ">
            <small>Need an account ? <a href="{{url_for('users.register')}}">Sign Up</a></small>
        </div>
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<div id="nav" class="container-fluid">
  <nav class=" navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('posts.home')}}"><b>Post <br> blog</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-evenly" id="navbarNav">
        <ul class="navbar-nav  me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('posts.home')}}">Home</a>
          </li>
          
          {% if current_user.is_authenticated %}
          
            <a class="nav-link active " href="{{url_for('posts.create')}}">Create Blog</a>
          <a class="nav-link active" href="{{url_for('users.account')}}">Account</a>
          <a class="nav-link active" href="{{url_for('users.logout')}}">Logout</a>
          <li class="nav-item ">
            <a  href="#" class="nav-link active" >
              {{current_user.username.title()}}
            </a>
         </li>
          {%else%}
          {%if request.url_rule.endpoint != 'register' %}
          <li class="nav-item">
            <a class="nav-link active" href="{{url_for('users.register')}}">Register</a>
          </li>
          {% endif %}
          {%if request.url_rule.endpoint != 'login'%}
          <li class="nav-item">
            <a class="nav-link active" href="{{url_for('users.login')}}">Login</a>
          </li>
          {%endif%}
        
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

app/templates/post.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid nav-page">
    <h3 class="text-center"><b>Post a Blog</b></h3>
    <div class="container  bg-light mt-2 p-3 w-50">
        <form action="" method="post" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            
            
            <div class="form-group">
                {{form.title.label(class='form-control-label')}}
                    {% if form.title.errors %}
                        {{form.title(class='form-control is-invalid')}}
                            {% for error in form.title.errors %}
                                <div class="invalid-feedback">
                                    {{error}}
                                </div>
                            {% endfor %}
                    {% else %}
                        {{form.title(class='form-control bg-transparent',placeholder="Enter Blog Title")}}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.description.label(class='form-control-label')}}
                    {% if form.description.errors %}
                    {{form.description(class='form-control is-invalid')}}
                        {% for error in form.description.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                {% else %}
                    {{form.description(class='form-control bg-transparent',placeholder="Enter Blog Description")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.content.label(class='form-control-label')}}
                    {% if form.content.errors %}
                    {{form.content(class='form-control is-invalid')}}
                        {% for error in form.content.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                {% else %}
                    {{form.content(class='form-control bg-transparent',placeholder="Enter Blog Content")}}
                {% endif %}
            </div>
           
           
            <div class="text-center my-3">
                {{form.submit(class='btn btn-outline post_submit')}}
            </div>
        </form>
     
    </div>
</div>

{% endblock %}

app/templates/reads.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
      
    <div class="row row-cols-1 row-cols-md-2 g-4">
  

      <div class="col ">
        <div class="card">
            <div class="row  p-2">
                <div class="col-md-8"></div>
             
              <div class="col-md-2 mx-auto mt-auto mb-auto text-muted">
                  <small>{{posts.author.username}}</small>
                  <br>
                  <small>{{posts.date_created.strftime('%Y-%m-%d')}}</small>
              </div>
            </div>
          <div class="card-body">
            <h5 class="card-title">{{posts.title}}</h5>
            <p class="card-text lead">{{posts.description}}</p>
            <div class="d-flex justify-content-around">
             
              <a  data-bs-toggle="collapse" href="#comments{{posts.id}}" class="lead text-decoration-none ">
                <img src="{{url_for('static',filename='/assets/comment.svg')}}" height="30" alt=""> 
              </a>
               
            </div>
            <div id="comments{{posts.id}}">

              <div class=" comments">

              
              </div>

              
            </div>
          </div>
        </div>
      </div>
 
     
</div>
{% endblock %}

app/templates/recover.html
{% extends 'base.html' %}
{% block body %}
<div class="container nav-page">
    <div class="container nav-container bg-light mt-2 p-3">
        <form action="" method="post">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.email.label(class='form-control-label')}}
                    {% if form.email.errors %}
                    {{form.email(class='form-control is-invalid')}}
                        {% for error in form.email.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                {% else %}
                    {{form.email(class='form-control')}}
                {% endif %}
            </div>
            <div class="text-center mt-3">
                {{form.submit(class='btn btn-outline')}}
            </div>
         
        </form>
    
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid nav-page">
    <div class="container form-container bg-sucess mt-2 p-3">
        <form action="" method="post">
            {{form.hidden_tag()}}
            <legend class="border-bottom ">Register</legend>
            <div class="form-group">
                {{form.username.label(class='form-control-label')}}
                    {% if form.username.errors %}
                        {{form.username(class='form-control is-invalid')}}
                            {% for error in form.username.errors %}
                                <div class="invalid-feedback">
                                    {{error}}
                                </div>
                            {% endfor %}
                    {% else %}
                        {{form.username(class='form-control')}}
                    {% endif %}
            </div>
            <div class="form-group">
                {{form.email.label(class='form-control-label')}}
                    {% if form.email.errors %}
                    {{form.email(class='form-control is-invalid')}}
                        {% for error in form.email.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                {% else %}
                    {{form.email(class='form-control')}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.password.label(class='form-control-label')}}
                {% if form.password.errors %}
                {{form.password(class='form-control is-invalid')}}
                    {% for error in form.password.errors %}
                        <div class="invalid-feedback">
                            {{error}}
                        </div>
                    {% endfor %}
            {% else %}
                {{form.password(class='form-control')}}
            {% endif %}
            </div>
            <div class="form-group">
                {{form.confirm_password.label(class='form-control-label')}}
                    {% if form.confirm_password.errors %}
                    {{form.confirm_password(class='form-control is-invalid')}}
                        {% for error in form.confirm_password.errors %}
                            <div class="invalid-feedback">
                                {{error}}
                            </div>
                        {% endfor %}
                   {% else %}
                    {{form.confirm_password(class='form-control')}}
                   {% endif %}
            </div>
            <div class="text-center my-3">
                {{form.submit(class='btn btn-outline')}}
            </div>
        </form>
        <div class="text-muted ">
            <small>Already have an account ? <a href="{{url_for('users.login')}}">Login</a></small>
        </div>
    </div>
</div>

{% endblock %}